### ISSUE TITLE
[Feature Request] URLs to go directly to a certain tab

### ISSUE THREAD

**Issue by Mar-Veloz** [saschadiercks/browserStartpage#7]
It would be awesome to be able to generate URLs to link directly to a particular tab. For example, if I have a tab named "Work" and a tab named "Streaming," it would be cool if `<url>#Work` could take me directly to the "Work" tab, and `<url>#Streaming` could take me directly to the "Streaming" tab. That way, I could set the Streaming tab as a homepage on my HTPC, and the Work tab as a homepage on my work computer.

Thanks so much for creating this fantastic webapp!

**Comment by saschadiercks** [comment]
Hi,
thanks for the suggestion and the kind words. This should be really easy to implement but for clarification:
The page currently stores the last opened tab in localStorage so revisiting will open the tab you had open, when you last left.
My idea is to take the hash from the url and if it exists, overwrite the default-behavior. This way we can use both functionalities.

Best regards,
Sascha

**Comment by saschadiercks** [comment]
This should work now.
Add a hash to the url to open tabs via direct call like so: `yourUrl#tab-1`
You can just click on the desired tab and copy the url to use it as a direct call. Changing the hash currently doesn't reload the URL, because that should not be necessary.

Pushed to master. Updating the /assets/js/site.js is enough. :)

**Comment by Mar-Veloz** [comment]
Wow that was quick! Thank you so much!
